import {
  ShoppingCart, MessageSquare, Scale, IndianRupee, Building2, Bug,
  HelpCircle, DoorOpen, Users, Package, ClipboardCheck, Landmark,
  Wrench, Shield, Car, UserCheck, Briefcase, HardHat
} from 'lucide-react';
import { LucideIcon } from 'lucide-react';

export interface FeatureShowcaseData {
  title: string;
  tagline: string;
  description: string;
  audience: string[];
  capabilities: string[];
  route: string;
  category: string;
  icon: LucideIcon;
}

export const featureShowcaseMap: Record<string, FeatureShowcaseData> = {
  marketplace: {
    title: 'Marketplace',
    tagline: 'Buy & sell within your community',
    description: 'Residents browse products from verified sellers within their society, add to cart, and place orders with real-time tracking. Sellers manage inventory, pricing, and fulfillment from their dashboard.',
    audience: ['Resident', 'Seller', 'Society Admin'],
    capabilities: ['Product catalog with categories', 'Cart & multi-vendor checkout', 'Order tracking & status updates', 'Seller verification & analytics', 'Cross-community selling'],
    route: '/',
    category: 'marketplace',
    icon: ShoppingCart,
  },
  bulletin: {
    title: 'Community Bulletin',
    tagline: 'Society discussions, polls & events',
    description: 'A community board for announcements, discussions, polls, events with RSVP, and pinned posts. Keeps residents informed and engaged with their society happenings.',
    audience: ['Resident', 'Society Admin', 'Moderator'],
    capabilities: ['Posts with categories & attachments', 'Polls with deadlines', 'Event RSVPs', 'Comment threads & upvotes', 'Pin & archive posts'],
    route: '/community',
    category: 'governance',
    icon: MessageSquare,
  },
  disputes: {
    title: 'Dispute Resolution',
    tagline: 'Track and resolve community issues',
    description: 'Residents raise disputes with photo evidence and SLA-tracked resolution. Committee members acknowledge, investigate, and resolve issues with full audit trails.',
    audience: ['Resident', 'Society Admin'],
    capabilities: ['Photo evidence uploads', 'SLA deadline tracking', 'Anonymous reporting option', 'Committee notes & resolution', 'Category-based routing'],
    route: '/disputes',
    category: 'governance',
    icon: Scale,
  },
  finances: {
    title: 'Society Finances',
    tagline: 'Transparent expense tracking',
    description: 'Society admins record expenses with receipts. Residents view spending breakdowns with charts, flag suspicious entries, and track income vs. expenditure over time.',
    audience: ['Resident', 'Society Admin', 'Treasurer'],
    capabilities: ['Expense recording with receipts', 'Income vs expense charts', 'Spending pie charts by category', 'Resident expense flagging', 'Transparency dashboard'],
    route: '/society/finances',
    category: 'finance',
    icon: IndianRupee,
  },
  construction_progress: {
    title: 'Construction Progress',
    tagline: 'Tower-wise construction tracking',
    description: 'Track construction milestones per tower with photo updates, completion percentages, and timeline comparisons. Includes document vault for RERA documents and project Q&A.',
    audience: ['Resident', 'Builder', 'Society Admin'],
    capabilities: ['Tower-wise progress tracking', 'Photo milestone updates', 'Expected vs revised dates', 'RERA document vault', 'Project Q&A board'],
    route: '/society/progress',
    category: 'construction',
    icon: Building2,
  },
  snag_management: {
    title: 'Snag Management',
    tagline: 'Report and track construction defects',
    description: 'Residents report construction defects (snags) with photos and location. Builders track, acknowledge, and fix issues. Collective escalation triggers when multiple residents report similar problems.',
    audience: ['Resident', 'Builder', 'Society Admin'],
    capabilities: ['Photo-based snag reporting', 'Priority & category tagging', 'Builder acknowledgment flow', 'Collective escalation system', 'Fix verification by resident'],
    route: '/society/snags',
    category: 'construction',
    icon: Bug,
  },
  help_requests: {
    title: 'Help Requests',
    tagline: 'Neighbor-to-neighbor assistance',
    description: 'Residents post requests for help (lending items, carpooling, pet sitting) with expiry timers. Neighbors respond and coordinate directly within the community.',
    audience: ['Resident'],
    capabilities: ['Tagged help categories', 'Auto-expiring requests', 'Response tracking', 'Community goodwill building', 'Quick post creation'],
    route: '/community',
    category: 'governance',
    icon: HelpCircle,
  },
  visitor_management: {
    title: 'Visitor Management',
    tagline: 'Gate entry & visitor tracking',
    description: 'Residents pre-approve visitors, generate QR passes, and get real-time notifications when visitors arrive. Guards verify entries with OTP or QR scanning.',
    audience: ['Resident', 'Security Guard', 'Society Admin'],
    capabilities: ['QR-based visitor passes', 'Real-time entry notifications', 'Resident confirmation flow', 'Entry log history', 'Denied entry tracking'],
    route: '/gate-entry',
    category: 'operations',
    icon: DoorOpen,
  },
  domestic_help: {
    title: 'Domestic Help',
    tagline: 'Maid, cook & driver management',
    description: 'Residents register domestic workers with live photos. Workers get daily gate passes validated by shift schedules and assigned flats. Attendance is automatically tracked via gate entries.',
    audience: ['Resident', 'Security Guard', 'Society Admin'],
    capabilities: ['Live photo registration', 'Shift & schedule validation', 'Flat assignment management', 'Gate entry attendance tracking', 'Worker status management'],
    route: '/domestic-help',
    category: 'operations',
    icon: Users,
  },
  parcel_management: {
    title: 'Parcel Management',
    tagline: 'Track deliveries at the gate',
    description: 'Guards log incoming parcels at the gate. Residents get notified and can track uncollected packages. Reduces lost deliveries and provides pickup confirmation.',
    audience: ['Resident', 'Security Guard'],
    capabilities: ['Parcel logging at gate', 'Resident notifications', 'Uncollected parcel alerts', 'Pickup confirmation', 'Delivery history'],
    route: '/parcels',
    category: 'operations',
    icon: Package,
  },
  inspection: {
    title: 'Inspection Checklist',
    tagline: 'Flat handover inspection',
    description: 'Structured checklist for flat inspections during handover. Residents and inspectors go room-by-room documenting issues with photos before accepting possession.',
    audience: ['Resident', 'Builder', 'Inspector'],
    capabilities: ['Room-wise checklists', 'Photo documentation', 'Issue severity marking', 'Digital sign-off', 'Report generation'],
    route: '/inspection',
    category: 'construction',
    icon: ClipboardCheck,
  },
  payment_milestones: {
    title: 'Payment Milestones',
    tagline: 'Track construction-linked payments',
    description: 'Track payment schedules tied to construction milestones. Residents see upcoming dues, payment history, and can verify milestone completion before releasing payments.',
    audience: ['Resident', 'Builder'],
    capabilities: ['Milestone-linked payments', 'Due date reminders', 'Payment history', 'Completion verification', 'Receipt tracking'],
    route: '/payment-milestones',
    category: 'finance',
    icon: Landmark,
  },
  maintenance: {
    title: 'Maintenance',
    tagline: 'Society maintenance requests',
    description: 'Residents submit maintenance requests for common areas and individual flats. Society admins assign, track, and resolve maintenance tasks with priority management.',
    audience: ['Resident', 'Society Admin', 'Maintenance Staff'],
    capabilities: ['Request submission with photos', 'Priority assignment', 'Status tracking', 'Assignment to staff', 'Resolution history'],
    route: '/maintenance',
    category: 'operations',
    icon: Wrench,
  },
  guard_kiosk: {
    title: 'Guard Kiosk',
    tagline: 'Security guard dashboard',
    description: 'A dedicated interface for security guards to manage gate entries, verify visitors via QR/OTP, validate worker passes, log parcels, and handle emergency situations.',
    audience: ['Security Guard', 'Society Admin'],
    capabilities: ['QR & OTP verification', 'Worker pass validation', 'Parcel logging', 'Emergency alerts', 'Shift-based access'],
    route: '/guard-kiosk',
    category: 'operations',
    icon: Shield,
  },
  vehicle_parking: {
    title: 'Vehicle Parking',
    tagline: 'Parking slot management',
    description: 'Manage assigned parking slots, track visitor parking, and handle parking violations. Residents register vehicles and guards verify parking authorization.',
    audience: ['Resident', 'Security Guard', 'Society Admin'],
    capabilities: ['Slot assignment', 'Vehicle registration', 'Visitor parking passes', 'Violation reporting', 'Parking history'],
    route: '/vehicle-parking',
    category: 'operations',
    icon: Car,
  },
  resident_identity_verification: {
    title: 'Resident Verification',
    tagline: 'Identity verification for residents',
    description: 'Verify resident identities during onboarding with document uploads and admin review. Ensures only genuine residents access society features and services.',
    audience: ['Resident', 'Society Admin'],
    capabilities: ['Document upload', 'Admin review workflow', 'Approval/rejection flow', 'Verified badge display', 'Re-verification requests'],
    route: '/security-verify',
    category: 'governance',
    icon: UserCheck,
  },
  worker_marketplace: {
    title: 'Worker Marketplace',
    tagline: 'Hire skilled workers from your community',
    description: 'Residents post job requests and browse available workers within the society. Workers accept jobs, get rated, and build reputation through completed tasks.',
    audience: ['Resident', 'Worker'],
    capabilities: ['Job posting & browsing', 'Worker profiles & ratings', 'Job acceptance flow', 'Completion & review', 'Skill-based matching'],
    route: '/worker-hire',
    category: 'marketplace',
    icon: Briefcase,
  },
  workforce_management: {
    title: 'Workforce Management',
    tagline: 'Manage society workers & contractors',
    description: 'Society admins register, track, and manage all workers (plumbers, electricians, cleaners) with live photo capture, shift schedules, gate validation, and performance tracking.',
    audience: ['Society Admin', 'Security Guard', 'Builder'],
    capabilities: ['Worker registration with live photo', 'Shift & schedule management', 'Gate entry validation', 'Flat assignment tracking', 'Rating & performance history'],
    route: '/workforce',
    category: 'operations',
    icon: HardHat,
  },
};
