// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { capacitorStorage } from '@/lib/capacitor-storage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use capacitorStorage for ALL platforms — on web it delegates to localStorage,
    // on native it uses @capacitor/preferences (persistent UserDefaults / SharedPreferences).
    // This eliminates the race condition of patching storage after client creation.
    storage: capacitorStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
