// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { capacitorStorage } from '@/lib/capacitor-storage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// NOTE: We intentionally do not bind generated Database types here yet because
// this project is migrating a large schema in batches.
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use capacitorStorage for ALL platforms — on web it delegates to localStorage,
    // on native it uses @capacitor/preferences (persistent UserDefaults / SharedPreferences).
    storage: capacitorStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
